<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="lidar_radius" value="0.03"/>

    <xacro:property name="lidar_length" value="0.03"/>
    <link name="laser_scan">
        <visual>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_length}"/>
            </geometry>
            <origin xyz="0.0 ${lidar_radius} ${lidar_length/2}" rpy="0.0 0.0 0.0"/>
            <material name="black">
                <color rgba="0.0 0.0 0.0 1.0"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${lidar_radius}" length="${lidar_length}"/>
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        </collision>
        <xacro:cylinder m="1.0" r ="0.07" h ="0.05"
            xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
    </link>
    
    <joint name="base_top_laser_scan_joint" type="fixed">
        <origin xyz="0.0 ${-chassis_width/2} 0.0" rpy="0.0 0.0 0.0"/>
        
        <parent link="chassis_top"/>
        <child link="laser_scan"/>
    </joint>
</robot>