<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
<xacro:property name="camera_length" value="0.04"/>
<xacro:property name="camera_width" value="0.02"/>
<xacro:property name="camera_height" value="0.035"/>
    <link name="camera_link">
        <visual>
            <geometry>
                <box size="${camera_length} ${camera_width} ${camera_height}"/>
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 ${pi/2}"/>
            <material name="black">
                <color rgba="0.0 0.0 0.0 1.0"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <box size="${camera_length} ${camera_width} ${camera_height}"/>
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 ${pi/2}"/>
        </collision>
        <xacro:box m="0.2" l="0.02" w="0.02" h="0.035" xyz="0.0 0.0 0.0" rpy="0.0 0.0 ${pi/2}"/>
    </link>
    <joint name="base_top_camera_joint" type="fixed">
       <origin xyz="0.0 ${chassis_width/2} 0.0" rpy="0.0 0.0 ${pi/2}"/>
       
        <parent link="chassis_top"/>
        <child link="camera_link"/>
    </joint>
    <link name="camera_link_optical"/>

    <joint name="camera_optical_joint" type="fixed">
        <parent link="camera_link"/>
        <child link="camera_link_optical"/>
        <origin xyz="0 0 0" rpy="-1.57 0 -1.57"/>
    </joint>
</robot>